name: Shopkeepers
version: 1.13.1i
description: Custom villager shopkeepers
author: nisovin
website: http://dev.bukkit.org/server-mods/shopkeepers/

main: com.nisovin.shopkeepers.ShopkeepersPlugin

commands:
    shopkeeper:
        description: Test
        aliases: [shopkeepers]
        
permissions:
    shopkeeper.reload:
        description: Reloads the plugin
        default: op
    shopkeeper.create:
        description: Create and modify a shopkeeper
        default: true
    shopkeeper.bypass:
        description: Bypass player shop restrictions
        default: op
